#!/usr/bin/env bash
# Install t-workflow into the current repository, update it to a newer release, or
# replace the old template-based t-workflow. One command; it opens the PR itself.
#
#   curl -fsSL https://raw.githubusercontent.com/t-workflow/t-workflow/main/install.sh | bash -s -- [<tag>] [options]
#
#   <tag>               the release to install; default: the newest tag at the source
#   --check "<cmd>"     the build/test command for .t-workflow/config (else detected from the repo)
#   --from <url|path>   where to take the release from (default: the t-workflow repository)
#   --dir <path>        the repository to install into (default: the current directory)
#   --no-protect        do not change GitHub branch protection or merge settings
#   --no-pr             change files only: no issue, branch, record, commit, PR, or protection
#
# Mode is detected: adopt (no t-workflow), update (.t-workflow/VERSION present), or
# replace (.template-manifest.json present — the old template-based t-workflow, whose
# owned files are removed and whose local slots are carried into the new layout).
set -euo pipefail

SOURCE_URL="https://github.com/t-workflow/t-workflow.git"
OWNED="
.t-workflow/AGENTS.md
.t-workflow/scripts
.claude/skills/t-open
.claude/skills/t-plan
.claude/skills/t-work
.claude/skills/t-review
.claude/skills/t-ship
.claude/skills/t-cancel
.claude/skills/t-status
.claude/skills/t-drive
.claude/skills/t-update
.github/workflows/t-workflow.yml
docs/tasks/TEMPLATE.md
"
# Paths an earlier release owned and this one does not, each with the git blob id of
# every copy this repository ever shipped. An update removes the consumer's file at
# such a path only when its bytes are one of those — the release's own copy, never a
# file the consumer wrote under that name.
RETIRED="
.github/ISSUE_TEMPLATE/task.yml b774760dd3dad869983e021d21693afecd191646 7c86e3808849a3a36c1f534277a4adff8fdf10b7
"

note() { printf '%s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

tag=""; check_arg=""; from=""; dir="."; protect=yes; pr=yes
while [ $# -gt 0 ]; do
  case "$1" in
    --check) check_arg="$2"; shift 2 ;;
    --from) from="$2"; shift 2 ;;
    --dir) dir="$2"; shift 2 ;;
    --no-protect) protect=no; shift ;;
    --no-pr) pr=no; shift ;;
    -h|--help) sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option $1" ;;
    *) [ -z "$tag" ] && tag="$1" || die "unexpected argument $1"; shift ;;
  esac
done
source="${from:-$SOURCE_URL}"
if [ -z "$tag" ]; then
  [ -d "$source" ] && die "a tag is required with a local directory source"
  refs=$(git ls-remote --tags --refs "$source") || die "could not list tags at $source (see the error above)"
  # Only release-shaped tags compete; an unrelated tag never wins. Explicitly naming
  # any tag still installs it. The ordering is a zero-padded numeric key because
  # BSD sort (macOS) has no sort -V.
  tags=$(printf '%s\n' "$refs" | sed 's#^[0-9a-f]*[[:space:]]*refs/tags/##' | grep '^v[0-9]' || true)
  tag=$(printf '%s\n' "$tags" \
    | awk '{ t=$0; k=t; gsub(/[^0-9]+/, " ", k); n=split(k, p, " "); key=""; for (i=1; i<=n; i++) key=key sprintf("%09d", p[i]); print key "\t" t }' \
    | sort | tail -1 | cut -f2-)
  [ -n "$tag" ] || die "no tags at $source; pass one explicitly"
fi

cd "$dir" || die "no such directory: $dir"
git rev-parse --show-toplevel >/dev/null 2>&1 || die "$PWD is not a git repository"
cd "$(git rev-parse --show-toplevel)"

# --- mode -------------------------------------------------------------------------
# The old template-based t-workflow is recognised by its manifest when it has one, and
# otherwise by its shape: a repository generated by the old bootstrap never got a
# manifest (that arrived with the old /t-update), but always has CONSTITUTION.md and the
# old protected-paths.sh.
if [ -f .template-manifest.json ]; then mode=replace; why="found .template-manifest.json"
elif [ -f CONSTITUTION.md ] && [ -f .t-workflow/scripts/protected-paths.sh ]; then mode=replace; why="found CONSTITUTION.md and .t-workflow/scripts/protected-paths.sh, the old t-workflow's shape (no manifest)"
elif [ -f .t-workflow/VERSION ]; then mode=update; why="found .t-workflow/VERSION"
else mode=adopt; why="no t-workflow here"; fi
current=""; [ "$mode" = update ] && current=$(cat .t-workflow/VERSION)
[ "$mode" = update ] && [ "$current" = "$tag" ] && { note "already at $tag; nothing to do"; exit 0; }
note "mode: $mode → $tag ($why)"

if [ "$pr" = yes ]; then
  command -v gh >/dev/null || die "gh is required (or use --no-pr)"
  gh auth status >/dev/null 2>&1 || die "gh is not authenticated (or use --no-pr)"
fi
[ -z "$(git status --porcelain)" ] || die "the working tree is not clean; commit or set aside your changes first"

# --- source -----------------------------------------------------------------------
src=$(mktemp -d); trap 'rm -rf "$src"' EXIT
if [ -d "$source" ]; then
  note "source: $source (local directory, labelled $tag)"
  cp -R "$source"/. "$src"/
else
  note "source: $source at $tag"
  # Partial clone: full commit history (for the log between tags) but file contents
  # only for the tag checked out. A server without filter support falls back to a full clone.
  git clone -q --filter=blob:none --branch "$tag" "$source" "$src" || die "could not clone $tag"
fi
[ -f "$src/.t-workflow/AGENTS.md" ] || die "the source does not look like t-workflow"
if [ "$mode" = update ] && [ -d "$src/.git" ]; then
  note "changes from $current to $tag:"
  git -C "$src" log --oneline "$current..$tag" 2>/dev/null | sed 's/^/  /' || note "  (history between the two tags is not available)"
fi
trunk=$("$src/.t-workflow/scripts/trunk.sh")

# --- plan: refuse collisions, then say what will happen before anything changes --
# Everything below this point mutates the tree or GitHub; the plan prints first.
# In adopt mode every owned path must be absent: overwriting a repository's own
# `.claude/skills/t-open` or `.github/workflows/t-workflow.yml` is never a merge.
# The known aliases (CLAUDE.md, GEMINI.md, AGENTS.md, .t-workflow/config) are not in
# OWNED and still merge as before.
collisions=""
if [ "$mode" = adopt ]; then
  for p in $OWNED; do
    [ -e "$p" ] || [ -L "$p" ] || continue
    collisions="${collisions:+$collisions }$p"
  done
  [ -z "$collisions" ] || die "refusing to overwrite existing paths:$collisions — move them aside first (adopt mode writes only when absent)"
fi
retire=""
if [ "$mode" = update ]; then
  while read -r p ids; do
    [ -n "$p" ] && [ -f "$p" ] || continue
    case " $ids " in
      *" $(git hash-object "$p") "*) retire="${retire:+$retire }$p" ;;
      *) note "note: $p is no longer shipped; the copy here is not a release's, so it stays yours" ;;
    esac
  done <<< "$RETIRED"
fi
note "plan:"
if [ "$mode" = replace ]; then
  note "  remove: the old t-workflow's files (manifest entries, migrations, old CI and docs)"
elif [ -n "$retire" ]; then
  for p in $retire; do note "  remove: $p (retired; the copy here is the one an earlier release wrote)"; done
else
  note "  remove: (none)"
fi
note "  write:"
for p in $OWNED; do note "    $p"; done
note "    .t-workflow/VERSION"
note "  create when absent: .t-workflow/config, AGENTS.md, CLAUDE.md, GEMINI.md, .agents/skills"
[ "$mode" = replace ] && note "  create when absent: .github/workflows/build.yml (from the old CI slot's steps, when the slot held any)"
if [ "$pr" = yes ]; then
  if [ "$protect" = yes ]; then
    note "  settings: open an issue, a branch and a PR; set squash-merge settings and merge the t-workflow check into branch protection (existing rules kept)"
  else
    note "  settings: open an issue, a branch and a PR; leave GitHub branch protection and merge settings alone"
  fi
else
  note "  settings: change files only (--no-pr); GitHub settings untouched"
fi

# --- task: issue and branch --------------------------------------------------------
case "$mode" in
  adopt)   title="Adopt t-workflow $tag" ;;
  update)  title="Update t-workflow from $current to $tag" ;;
  replace) title="Replace the old t-workflow with t-workflow $tag" ;;
esac
id=""
if [ "$pr" = yes ]; then
  cur=$(git rev-parse --abbrev-ref HEAD)
  [ "$cur" = "$trunk" ] || die "run this from the trunk branch ($trunk); you are on $cur"
  git fetch -q origin
  body=$(mktemp)
  {
    echo "## Goal"
    case "$mode" in
      adopt)   echo "Install t-workflow $tag: the delivery workflow's skills, gate scripts, CI workflow, and record template, with this repository's own settings in \`.t-workflow/config\`." ;;
      update)  echo "Move t-workflow from $current to $tag by replacing every t-workflow-owned file with the release's copy. Consumer-owned files (\`AGENTS.md\`, \`.t-workflow/config\`) are untouched." ;;
      replace) echo "Remove the old template-based t-workflow (every file its manifest owns, its migrations, and its CI) and install t-workflow $tag in its place, carrying the old local slots into \`.t-workflow/config\` and \`AGENTS.md\`." ;;
    esac
    echo; echo "## Done when"
    echo "- \`.t-workflow/VERSION\` reads \`$tag\` and every path in the installer's owned set matches the release."
    echo "- \`.t-workflow/scripts/ci.sh\` passes on this PR."
    echo; echo "## Scope"
    echo "\`.t-workflow/\`, \`.claude/skills/t-*\`, \`.agents/skills\`, \`.github/workflows/t-workflow.yml\`, \`docs/tasks/\`, \`AGENTS.md\`, \`CLAUDE.md\`, \`GEMINI.md\`$([ "$mode" = replace ] && printf ', `.github/workflows/build.yml` (written once from the old CI slot)')"
    echo; echo "## Non-goals"
    echo "- Changing anything else in the repository."
    echo; echo "## Plan"; echo "### Allowed paths"
    printf '%s\n' $OWNED | sed 's/^/- `/; s/$/`/'
    echo "- \`.t-workflow/config\`, \`AGENTS.md\`, \`CLAUDE.md\`, \`GEMINI.md\`, \`.agents/skills\`, \`docs/tasks/\` — created or pointed at t-workflow when absent"
    [ "$mode" = replace ] && echo "- every path in \`.template-manifest.json\`, \`migrations/\`, \`.gitignore\` (markers stripped) — removed or cleaned"
    [ "$mode" = replace ] && echo "- \`.github/workflows/build.yml\` — this project's own build, written once from the old workflow's slot when absent"
    echo "### Risks"; echo "- The detected check command may be wrong: read \`.t-workflow/config\` in the diff."
    [ "$mode" = replace ] && echo "- Old local-slot content that did not map onto the new layout is listed in \`.t-workflow/REPLACED.md\` for a human to place."
    echo "### Checks"; echo "- \`.t-workflow/scripts/ci.sh\` — record, title, plan, blockers (the project's own CI runs its build)"
    echo "### Human checks"; echo "- none"
  } > "$body"
  url=$(gh issue create --title "$title" --body-file "$body"); rm -f "$body"
  id="${url##*/}"
  slug=$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' | cut -c1-40 | sed -E 's/-+$//')
  branch="wip/$id-$slug"
  git checkout -q -b "$branch" "origin/$trunk"
  note "issue #$id, branch $branch"
fi

# --- replace: remove the old template's files, keeping what its slots held --------
# What the old template shipped, by name. Applied with or without a manifest, so a
# consumer's own files under the same directories (its ADRs from 100 up, its l-* skills,
# its own workflows) are never touched.
OLD_SHIPPED="
CONSTITUTION.md
AGENTS.md
docs/workflow.md
docs/tasks/README.md
.github/workflows/ci.yml
.github/workflows/review-gate.yml
.github/ISSUE_TEMPLATE/task.yml
.github/ISSUE_TEMPLATE/initiative.yml
.github/ISSUE_TEMPLATE/config.yml
docs/adapters/FORGE.md
docs/adapters/MODEL.md
docs/adapters/OBSERVER.md
docs/adapters/PREVIEW.md
docs/adapters/TRACKER.md
docs/architecture/adoption.md
docs/architecture/collaboration-state.md
docs/architecture/confirmation-gates.md
docs/architecture/external-origin.md
docs/architecture/feedback-pass.md
docs/architecture/issue-templates.md
docs/architecture/local-slots.md
docs/architecture/manifest.md
docs/architecture/migrations.md
docs/architecture/verification.md
migrations
.template-manifest.json
"
old_shipped_globs() { # the old template's files that are only recognisable by pattern
  find .claude/skills -maxdepth 1 -type d -name 't-*' 2>/dev/null
  find .t-workflow/scripts -maxdepth 1 -name '*.sh' 2>/dev/null
  find docs/adr -maxdepth 1 -name '0[0-9][0-9]-*.md' 2>/dev/null
}
report=""
if [ "$mode" = replace ]; then
  if [ -f .template-manifest.json ]; then
    command -v jq >/dev/null || die "jq is required to read .template-manifest.json"
    n=$(jq -r '.files | keys | length' .template-manifest.json 2>/dev/null || echo 0)
    [ "${n:-0}" -gt 0 ] || die ".template-manifest.json lists no files; nothing would be removed safely — inspect it first"
  fi
  report=$(mktemp); report_used=no
  echo "# Replaced the old t-workflow" > "$report"
  echo >> "$report"; echo "Content the old local slots held that has no automatic place in the new layout. Place it by hand, then delete this file." >> "$report"
  old_check=""; old_docs=""; old_protected=""; old_model=""; old_notes=""; old_constraints=""; old_ci_steps=""; old_ci_timeout=""; old_skill_rows=""
  slots() { # <file>: each marked region, preceded by "@@ <last ## heading>"
    awk '/^## /{h=$0} /^[[:space:]]*#?[[:space:]]*<!-- local -->[[:space:]]*$/{on=1; print "@@ " h; next}
         /^[[:space:]]*#?[[:space:]]*<!-- \/local -->[[:space:]]*$/{on=0; next} on{print}' "$1"
  }
  placeholder() { printf '%s' "$1" | grep -v '^[[:space:]]*$' | head -1 | grep -qE '^\*\(reserved'; }
  harvest() { # <file> <kind>
    local f="$1" kind="$2" h="" buf="" seen=no
    [ -f "$f" ] || return 0
    flush() {
      [ "$seen" = yes ] || return 0
      [ -n "$h" ] || h="(top of file)"
      placeholder "$buf" && return 0
      [ -z "$(printf '%s' "$buf" | grep -v '^[[:space:]]*$')" ] && return 0                       # an empty slot
      case "$kind:$h" in
        agents:"## Checks")
          # The check slot's own placeholder ("1. **(none yet — no stack exists.)** … `npm test`, …")
          # carries example commands in backticks; it names no check.
          if printf '%s' "$buf" | grep -qE '^1\. '; then
            printf '%s' "$buf" | grep -qE '^1\. \*\*\(none' || old_check=$(printf '%s' "$buf" | grep -oE '`[^`]+`' | head -1 | tr -d '`' || true)
          else old_docs=$(printf '%s' "$buf" | grep -oE '`[^`]+`' | tr -d '`' | tr '\n' ' ' || true); fi ;;
        agents:"## The pipeline")
          old_skill_rows=$(printf '%s' "$buf" | grep -E '^\| `/' || true)
          rest=$(printf '%s' "$buf" | grep -vE '^\| `/|^\| Skill \| Stage \|$|^\|---\|---\|$|^[[:space:]]*$' || true)
          if [ -n "$rest" ]; then
            { echo; echo "## $f — $h (text beside the skill rows)"; echo; echo '```'; printf '%s\n' "$rest"; echo '```'; } >> "$report"; report_used=yes
          fi ;;
        agents:"## Reviewer model") old_model=$(printf '%s' "$buf" | sed -n 's/^Default reviewer model: *//p' | grep -v '^(none' | head -1 || true) ;;
        agents:"## Project notes") old_notes="$buf" ;;
        constitution:"## 3. Protected surfaces") old_protected=$(printf '%s' "$buf" | grep -oE '`[^`]+`' | tr -d '`' | tr '\n' ' ' || true) ;;
        constitution:"## 4. Stack & architecture") old_constraints="$buf" ;;
        ci:*)
          # Workflow steps in the old slot become the project's own build workflow; a timeout is carried into it.
          if printf '%s' "$buf" | grep -qE '^[[:space:]]*- (uses|name|run):'; then old_ci_steps="$old_ci_steps$buf"
          elif t=$(printf '%s' "$buf" | sed -n 's/^[[:space:]]*timeout-minutes:[[:space:]]*\([0-9]*\).*/\1/p' | head -1) && [ -n "$t" ]; then
            [ "$f" = .github/workflows/ci.yml ] && old_ci_timeout="$t" || true   # the build's own timeout; the review gate's is irrelevant now
          else { echo; echo "## $f — $h"; echo; echo '```'; printf '%s\n' "$buf"; echo '```'; } >> "$report"; report_used=yes; fi ;;
        *) { echo; echo "## $f — $h"; echo; echo '```'; printf '%s\n' "$buf"; echo '```'; } >> "$report"; report_used=yes ;;
      esac
    }
    while IFS= read -r line; do
      case "$line" in "@@ "*) flush; seen=yes; h="${line#@@ }"; buf="" ;; *) buf="$buf$line"$'\n' ;; esac
    done < <(slots "$f")
    flush
  }
  harvest AGENTS.md agents
  harvest CONSTITUTION.md constitution
  harvest .github/workflows/ci.yml ci
  harvest .github/workflows/review-gate.yml ci
  if [ -f .t-workflow/required-checks.local ]; then
    report_used=yes
    { echo; echo "## .t-workflow/required-checks.local"; echo; echo "The old template's list of extra required status checks. The new workflow's only required check is \`t-workflow\`; if these still matter, they belong in your own CI and branch protection."; echo; echo '```'; cat .t-workflow/required-checks.local; echo '```'; } >> "$report"
  fi
  if [ -f .template-manifest.json ]; then
    jq -r '.files | keys[]' .template-manifest.json | while IFS= read -r p; do
      [ "$p" = .gitignore ] && continue
      [ -e "$p" ] || [ -L "$p" ] || continue
      rm -rf "$p"
    done
  fi
  for p in $OLD_SHIPPED $(old_shipped_globs); do rm -rf "$p"; done
  rm -f .t-workflow/required-checks.local
  [ -f .gitignore ] && { grep -vE '^[[:space:]]*#?[[:space:]]*<!-- /?local -->[[:space:]]*$' .gitignore > .gitignore.new; mv .gitignore.new .gitignore; }
  find docs .github .claude .t-workflow -type d -empty -delete 2>/dev/null || true
  note "removed the old t-workflow's files"
fi

# --- replace: the project's own build workflow, from the old ci slot ----------------
# Written once, only when absent; from then on it is the project's file like any other.
if [ -n "${old_ci_steps:-}" ]; then
  if [ -f .github/workflows/build.yml ]; then
    { echo; echo "## .github/workflows/ci.yml — build steps"; echo; echo "This project already has a \`.github/workflows/build.yml\`, so the old workflow's build steps were not written there. Merge what you still need:"; echo; echo '```'; printf '%s\n' "$old_ci_steps"; echo '```'; } >> "$report"; report_used=yes
  else
    mkdir -p .github/workflows
    {
      echo "# This project's build. Written once by t-workflow's installer from the old workflow's"
      echo "# slot; it is this project's own file and no update touches it."
      echo "name: build"
      echo "on:"
      echo "  pull_request:"
      echo "  push:"
      echo "    branches: [$trunk]"
      echo "jobs:"
      echo "  build:"
      echo "    runs-on: ubuntu-latest"
      echo "    timeout-minutes: ${old_ci_timeout:-30}"
      echo "    steps:"
      echo "      - uses: actions/checkout@v4"
      echo "        with:"
      echo "          fetch-depth: 0"
      # Dedent to the list marker; a line shallower than that (a column-zero comment) is
      # indented to the marker instead of cut. The old build step guarded itself with an
      # output of a docs-only step that no longer exists; that clause goes. A step that
      # ran one of the old template's scripts is dropped, with the comments above it.
      printf '%s' "$old_ci_steps" | awk '
        { sub(/\r$/, "") }
        /^[[:space:]]*$/ { next }
        { match($0, /^[[:space:]]*/); ind = RLENGTH; if ($0 ~ /^[[:space:]]*- /) { if (min == "" || ind < min) min = ind }; lines[++n] = $0; inds[n] = ind }
        END {
          for (i = 1; i <= n; i++) {
            l = lines[i]; if (inds[i] >= min) l = substr(l, min + 1); else { sub(/^[[:space:]]*/, "", l) }
            sub(/ *&& *steps\.docs-only\.outputs\.docs_only *!= *'"'"'true'"'"'/, "", l)
            if (l ~ /^- /) { flush(); step = l "\n"; instep = 1; drop = (l ~ /\.t-workflow\/scripts\//) }
            else if (l ~ /^#/) { flush(); lead = lead l "\n" }          # a comment at the list level belongs to the next step
            else if (instep) { step = step l "\n"; if (l ~ /\.t-workflow\/scripts\//) drop = 1 }
            else { lead = lead l "\n" }
          }
          flush(); if (lead != "") printf "%s", lead   # a trailing comment with no step after it is kept
        }
        function flush() { if (step != "") { if (!drop) printf "%s%s", lead, step; lead = ""; step = ""; drop = 0; instep = 0 } }' | sed 's/^/      /'
    } > .github/workflows/build.yml
    wrote_build=yes; note "wrote .github/workflows/build.yml from the old CI slot's steps (yours from now on)"
  fi
fi

# --- copy the owned set ------------------------------------------------------------
for p in $OWNED; do
  rm -rf "$p"; mkdir -p "$(dirname "$p")"; cp -R "$src/$p" "$p"
done
for p in $retire; do rm -f "$p"; rmdir "$(dirname "$p")" 2>/dev/null || true; note "removed $p (retired)"; done
printf '%s\n' "$tag" > .t-workflow/VERSION
chmod +x .t-workflow/scripts/*.sh
mkdir -p .agents docs/tasks
[ -e .agents/skills ] || ln -s ../.claude/skills .agents/skills
if [ -n "$report" ]; then
  if [ "$report_used" = yes ]; then mv "$report" .t-workflow/REPLACED.md; note "old slot content with no automatic home: .t-workflow/REPLACED.md"; else rm -f "$report"; fi
fi
note "installed the owned set"

# --- consumer-owned files, created only when absent --------------------------------
detect_check() {
  if [ -f package.json ]; then echo "npm test"
  elif [ -f Gemfile ]; then { [ -d spec ] && echo "bundle exec rspec"; } || echo "bundle exec rake test"
  elif [ -f Cargo.toml ]; then echo "cargo test"
  elif [ -f go.mod ]; then echo "go test ./..."
  elif [ -f pyproject.toml ] || [ -f pytest.ini ] || [ -f setup.py ]; then echo "pytest"
  elif [ -f mix.exs ]; then echo "mix test"
  elif [ -f build.gradle ] || [ -f build.gradle.kts ]; then echo "./gradlew test"
  elif [ -f pom.xml ]; then echo "mvn test"
  elif [ -f Makefile ] && grep -qE '^test:' Makefile; then echo "make test"
  fi
}
default_config() {
  cat <<'CONFIG'
# t-workflow configuration. Owned by this repository; never touched by an update.
# Parsed by .t-workflow/scripts/*, never executed: key="value" lines only, no quotes
# inside the value, no variables. Any other assignment is ignored and said on stderr.

# Build/test command the agent runs locally before opening a PR (empty = none yet).
# CI does not run it; the project's own CI does.
check=""

# Extra protected globs, space-separated, on top of the built-in set
# (e.g. "db/migrate/* config/*"). A protected diff needs a plan and a cold review.
protected=""

# Extra documentation globs, space-separated, on top of *.md and docs/*
# (e.g. "site/*"). A documentation-only diff skips check 1.
docs=""

# Branch globs exempt from the task gates in CI (e.g. "dependabot/*").
exempt=""

# Model /t-review's subagent reviewer runs under (empty = the invoking session's own).
reviewer_model=""
CONFIG
}
if [ ! -f .t-workflow/config ]; then
  default_config > .t-workflow/config
  chk="${check_arg:-${old_check:-$(detect_check)}}"
  [ -n "$chk" ] && sed -i.bak "s|^check=\"\"|check=\"$(printf '%s' "$chk" | sed 's/[|&\\]/\\&/g')\"|" .t-workflow/config
  [ -n "${old_protected:-}" ] && sed -i.bak "s|^protected=\"\"|protected=\"${old_protected% }\"|" .t-workflow/config
  [ -n "${old_docs:-}" ] && sed -i.bak "s|^docs=\"\"|docs=\"${old_docs% }\"|" .t-workflow/config
  [ -n "${old_model:-}" ] && sed -i.bak "s|^reviewer_model=\"\"|reviewer_model=\"$old_model\"|" .t-workflow/config
  rm -f .t-workflow/config.bak
  note "wrote .t-workflow/config (check: ${chk:-none detected})"
else
  # A release may add a key: append what this config lacks, with its comment, leaving present values alone.
  def=$(mktemp); default_config > "$def"
  # Earlier releases' default comments said CI runs the check; rewrite those exact lines, values
  # untouched. awk, not sed: a newline in a sed replacement is not portable to macOS.
  awk '
    $0 == "# Build/test command, run as check 1 (empty = no check 1 yet)." {
      print "# Build/test command the agent runs locally before opening a PR (empty = none yet)."
      print "# CI does not run it; the project'"'"'s own CI does."; next }
    $0 == "# Branch globs exempt from the task gates in CI (e.g. \"dependabot/*\"). Check 1 still runs." {
      print "# Branch globs exempt from the task gates in CI (e.g. \"dependabot/*\")."; next }
    $0 == "# Shell syntax: key=\"value\". Read by .t-workflow/scripts/*." {
      print "# Parsed by .t-workflow/scripts/*, never executed: key=\"value\" lines only, no quotes"
      print "# inside the value, no variables. Any other assignment is ignored and said on stderr."; next }
    { print }' .t-workflow/config > .t-workflow/config.new && mv .t-workflow/config.new .t-workflow/config
  rm -f .t-workflow/config.bak
  [ -z "$(tail -c1 .t-workflow/config)" ] || echo >> .t-workflow/config   # end with a newline before appending
  for key in $(grep -oE '^[a-z_]+=' "$def" | tr -d =); do
    grep -q "^$key=" .t-workflow/config && continue
    awk -v k="$key=" '/^#/{b=b $0 "\n"; next} index($0,k)==1{printf "\n%s%s\n", b, $0; exit} {b=""}' "$def" >> .t-workflow/config
    note "config: added $key with its default"
  done
  rm -f "$def"
  if [ -n "$check_arg" ]; then
    sed -i.bak "s|^check=.*|check=\"$(printf '%s' "$check_arg" | sed 's/[|&\\]/\\&/g')\"|" .t-workflow/config; rm -f .t-workflow/config.bak
  fi
fi

pointer='Read `.t-workflow/AGENTS.md` first — the delivery workflow for this repository.'
if [ ! -e AGENTS.md ] && [ -f CLAUDE.md ] && [ ! -L CLAUDE.md ]; then mv CLAUDE.md AGENTS.md; fi
if [ -L AGENTS.md ] && [ ! -e AGENTS.md ]; then rm -f AGENTS.md; fi
if [ ! -e AGENTS.md ]; then
  { echo "$pointer"; echo; echo "## Project notes"; echo
    if [ -n "${old_notes:-}" ]; then printf '%s\n' "$old_notes"; else echo "*(this repository's own session-start instructions)*"; fi
    [ -n "${old_constraints:-}" ] && { echo; echo "## Constraints"; echo; printf '%s\n' "$old_constraints"; }
    [ -n "${old_skill_rows:-}" ] && { echo; echo "## Skills of this repository"; echo; echo "| Skill | Stage |"; echo "|---|---|"; printf '%s\n' "$old_skill_rows"; }
  } > AGENTS.md
elif ! grep -qF '.t-workflow/AGENTS.md' AGENTS.md; then
  { echo "$pointer"; echo; cat AGENTS.md; } > AGENTS.md.new && mv AGENTS.md.new AGENTS.md
fi
for alias in CLAUDE.md GEMINI.md; do [ -e "$alias" ] || [ -L "$alias" ] || ln -s AGENTS.md "$alias"; done

# --- --no-pr stops here -------------------------------------------------------------
if [ "$pr" = no ]; then
  note "done (no PR): review the changes with git status / git diff"
  exit 0
fi

# --- record, commit, PR, protection ------------------------------------------------
rec=$(.t-workflow/scripts/record.sh create "$id")
git add -A
git commit -q -m "$title" -m "Task: #$id — $rec"
git push -q -u origin "$branch"
prbody=$(mktemp)
{
  echo "Closes #$id"; echo
  echo "$title. Every t-workflow-owned file is the release's copy; \`.t-workflow/config\` and \`AGENTS.md\` are this repository's own."
  if [ "$mode" = replace ]; then
    [ "${wrote_build:-}" = yes ] && echo "The old workflow's build steps are now this project's own \`.github/workflows/build.yml\`."
    [ -f .t-workflow/REPLACED.md ] && echo "Old local-slot content with no automatic home is in \`.t-workflow/REPLACED.md\`."
  fi
  echo; echo "## Checks run"; echo "- \`.t-workflow/scripts/ci.sh\` — runs on this PR"
} > "$prbody"
if [ "$mode" = update ]; then
  prurl=$(gh pr create --draft --title "[$id] $title" --body-file "$prbody")
else
  prurl=$(gh pr create --title "[$id] $title" --body-file "$prbody")
fi
rm -f "$prbody"
if [ "$protect" = yes ]; then
  pflags=(); [ "$mode" = replace ] && pflags+=(--remove checks --remove cold-review); [ "${wrote_build:-}" = yes ] && pflags+=(--add build)
  .t-workflow/scripts/protect.sh ${pflags[@]+"${pflags[@]}"} || true
fi
note ""
note "PR: $prurl"
case "$mode" in
  update) note "next: /t-drive $id (cold review, then the merge question)" ;;
  *) note "next: review the PR and merge it; the workflow is in force from then on" ;;
esac
